@startuml

start
: **RetryUtils_ParamsReset()**;
repeat
	: Server communication attempt;
	if (Success) then (no)
    	: **RetryUtils_BackoffAndSleep()**;
    else (yes)
    endif
repeat while (Server communication failed &&\nRetries not exhausted) is (yes)
-> no;
stop

@enduml