/*
 * Copyright (C) 2019 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * @file aws_iot_tests_jobs_serialize.c
 * @brief Tests for the Jobs JSON functions.
 */

/* The config header is always included first. */
#include "iot_config.h"

/* SDK initialization include. */
#include "iot_init.h"

/* Jobs internal include. */
#include "private/aws_iot_jobs_internal.h"

/* Test framework includes. */
#include "unity_fixture.h"

/* JSON utilities include. */
#include "iot_json_utils.h"

/*-----------------------------------------------------------*/

/**
 * @brief Test group for Jobs Serialize tests.
 */
TEST_GROUP( Jobs_Unit_Serialize );

/*-----------------------------------------------------------*/

/**
 * @brief Test setup for Jobs Serialize tests.
 */
TEST_SETUP( Jobs_Unit_Serialize )
{
    /* Initialize SDK. */
    TEST_ASSERT_EQUAL_INT( true, IotSdk_Init() );

    /* Initialize the Jobs library. */
    TEST_ASSERT_EQUAL( AWS_IOT_JOBS_SUCCESS, AwsIotJobs_Init( 0 ) );
}

/*-----------------------------------------------------------*/

/**
 * @brief Test tear down for Jobs Serialize tests.
 */
TEST_TEAR_DOWN( Jobs_Unit_Serialize )
{
    /* Clean up libraries. */
    AwsIotJobs_Cleanup();
    IotSdk_Cleanup();
}

/*-----------------------------------------------------------*/

/**
 * @brief Test group runner for Jobs Serialize tests.
 */
TEST_GROUP_RUNNER( Jobs_Unit_Serialize )
{
    RUN_TEST_CASE( Jobs_Unit_Serialize, SerializeGetPending );
    RUN_TEST_CASE( Jobs_Unit_Serialize, SerializeStartNextClientToken );
    RUN_TEST_CASE( Jobs_Unit_Serialize, SerializeStartNextStepTimeout );
    RUN_TEST_CASE( Jobs_Unit_Serialize, SerializeStartNextStatusDetails );
}

/*-----------------------------------------------------------*/

/**
 * @brief Tests generation of JSON documents for GET PENDING requests.
 */
TEST( Jobs_Unit_Serialize, SerializeGetPending )
{
    AwsIotJobsError_t status = AWS_IOT_JOBS_STATUS_PENDING;
    _jobsOperation_t operation = { .link = { 0 } };
    AwsIotJobsRequestInfo_t requestInfo = AWS_IOT_JOBS_REQUEST_INFO_INITIALIZER;
    const char * pClientToken = NULL;
    size_t clientTokenLength = 0;

    /* Generate request with autogenerated client token. */
    status = _AwsIotJobs_GenerateJsonRequest( JOBS_GET_PENDING,
                                              &requestInfo,
                                              NULL,
                                              &operation );
    TEST_ASSERT_EQUAL( AWS_IOT_JOBS_SUCCESS, status );

    /* Check that a client token is present. */
    TEST_ASSERT_EQUAL_INT( true, IotJsonUtils_FindJsonValue( operation.pJobsRequest,
                                                             operation.jobsRequestLength,
                                                             AWS_IOT_CLIENT_TOKEN_KEY,
                                                             AWS_IOT_CLIENT_TOKEN_KEY_LENGTH,
                                                             &pClientToken,
                                                             &clientTokenLength ) );
    TEST_ASSERT_EQUAL_PTR( pClientToken, operation.pClientToken );
    TEST_ASSERT_EQUAL( clientTokenLength, operation.clientTokenLength );

    /* Free request document generated by serializer. */
    AwsIotJobs_FreeString( ( void * ) operation.pJobsRequest );

    /* Generate request with custom client token. */
    requestInfo.pClientToken = "test";
    requestInfo.clientTokenLength = 4;
    status = _AwsIotJobs_GenerateJsonRequest( JOBS_GET_PENDING,
                                              &requestInfo,
                                              NULL,
                                              &operation );

    /* Check that the custom client token is present. */
    TEST_ASSERT_EQUAL_INT( true, IotJsonUtils_FindJsonValue( operation.pJobsRequest,
                                                             operation.jobsRequestLength,
                                                             AWS_IOT_CLIENT_TOKEN_KEY,
                                                             AWS_IOT_CLIENT_TOKEN_KEY_LENGTH,
                                                             &pClientToken,
                                                             &clientTokenLength ) );
    TEST_ASSERT_EQUAL_PTR( pClientToken, operation.pClientToken );
    TEST_ASSERT_EQUAL( 6, operation.clientTokenLength );
    TEST_ASSERT_EQUAL_STRING_LEN( "\"test\"", operation.pClientToken, 6 );

    /* Free request document generated by serializer. */
    AwsIotJobs_FreeString( ( void * ) operation.pJobsRequest );
}

/*-----------------------------------------------------------*/

/**
 * @brief Tests generation of client token in JSON documents for START NEXT
 * requests.
 */
TEST( Jobs_Unit_Serialize, SerializeStartNextClientToken )
{
    AwsIotJobsError_t status = AWS_IOT_JOBS_STATUS_PENDING;
    _jobsOperation_t operation = { .link = { 0 } };
    AwsIotJobsRequestInfo_t requestInfo = AWS_IOT_JOBS_REQUEST_INFO_INITIALIZER;
    AwsIotJobsUpdateInfo_t updateInfo = AWS_IOT_JOBS_UPDATE_INFO_INITIALIZER;
    const char * pJsonValue = NULL;
    size_t jsonValueLength = 0;

    /* Generate request with only autogenerated client token. */
    status = _AwsIotJobs_GenerateJsonRequest( JOBS_START_NEXT,
                                              &requestInfo,
                                              &updateInfo,
                                              &operation );
    TEST_ASSERT_EQUAL( AWS_IOT_JOBS_SUCCESS, status );

    /* Check that a client token is present. */
    TEST_ASSERT_EQUAL_INT( true, IotJsonUtils_FindJsonValue( operation.pJobsRequest,
                                                             operation.jobsRequestLength,
                                                             AWS_IOT_CLIENT_TOKEN_KEY,
                                                             AWS_IOT_CLIENT_TOKEN_KEY_LENGTH,
                                                             &pJsonValue,
                                                             &jsonValueLength ) );
    TEST_ASSERT_EQUAL_PTR( pJsonValue, operation.pClientToken );
    TEST_ASSERT_EQUAL( jsonValueLength, operation.clientTokenLength );

    /* Check that the step token is -1. */
    TEST_ASSERT_EQUAL_INT( true, IotJsonUtils_FindJsonValue( operation.pJobsRequest,
                                                             operation.jobsRequestLength,
                                                             "stepTimeoutInMinutes",
                                                             20,
                                                             &pJsonValue,
                                                             &jsonValueLength ) );
    TEST_ASSERT_EQUAL( 2, jsonValueLength );
    TEST_ASSERT_EQUAL_STRING_LEN( "-1", pJsonValue, 2 );

    /* Free request document generated by serializer. */
    AwsIotJobs_FreeString( ( void * ) operation.pJobsRequest );

    /* Generate request with custom client token. */
    requestInfo.pClientToken = "test";
    requestInfo.clientTokenLength = 4;

    status = _AwsIotJobs_GenerateJsonRequest( JOBS_START_NEXT,
                                              &requestInfo,
                                              &updateInfo,
                                              &operation );
    TEST_ASSERT_EQUAL( AWS_IOT_JOBS_SUCCESS, status );

    /* Check that the custom client token is present. */
    TEST_ASSERT_EQUAL_INT( true, IotJsonUtils_FindJsonValue( operation.pJobsRequest,
                                                             operation.jobsRequestLength,
                                                             AWS_IOT_CLIENT_TOKEN_KEY,
                                                             AWS_IOT_CLIENT_TOKEN_KEY_LENGTH,
                                                             &pJsonValue,
                                                             &jsonValueLength ) );
    TEST_ASSERT_EQUAL_PTR( pJsonValue, operation.pClientToken );
    TEST_ASSERT_EQUAL( 6, operation.clientTokenLength );
    TEST_ASSERT_EQUAL_STRING_LEN( "\"test\"", pJsonValue, 6 );

    /* Free request document generated by serializer. */
    AwsIotJobs_FreeString( ( void * ) operation.pJobsRequest );
}

/*-----------------------------------------------------------*/

/**
 * @brief Tests generation of step timeout in JSON documents for START NEXT
 * requests.
 */
TEST( Jobs_Unit_Serialize, SerializeStartNextStepTimeout )
{
    AwsIotJobsError_t status = AWS_IOT_JOBS_STATUS_PENDING;
    _jobsOperation_t operation = { .link = { 0 } };
    AwsIotJobsRequestInfo_t requestInfo = AWS_IOT_JOBS_REQUEST_INFO_INITIALIZER;
    AwsIotJobsUpdateInfo_t updateInfo = AWS_IOT_JOBS_UPDATE_INFO_INITIALIZER;
    const char * pJsonValue = NULL;
    size_t jsonValueLength = 0;

    /* Generate request with step timeout. */
    updateInfo.stepTimeoutInMinutes = 3600;

    status = _AwsIotJobs_GenerateJsonRequest( JOBS_START_NEXT,
                                              &requestInfo,
                                              &updateInfo,
                                              &operation );
    TEST_ASSERT_EQUAL( AWS_IOT_JOBS_SUCCESS, status );

    /* Check that the step timeout is present. */
    TEST_ASSERT_EQUAL_INT( true, IotJsonUtils_FindJsonValue( operation.pJobsRequest,
                                                             operation.jobsRequestLength,
                                                             "stepTimeoutInMinutes",
                                                             20,
                                                             &pJsonValue,
                                                             &jsonValueLength ) );
    TEST_ASSERT_EQUAL( 4, jsonValueLength );
    TEST_ASSERT_EQUAL_STRING_LEN( "3600", pJsonValue, 4 );

    /* Free request document generated by serializer. */
    AwsIotJobs_FreeString( ( void * ) operation.pJobsRequest );
}

/*-----------------------------------------------------------*/

/**
 * @brief Tests generation of status details in JSON documents for START NEXT
 * requests.
 */
TEST( Jobs_Unit_Serialize, SerializeStartNextStatusDetails )
{
    AwsIotJobsError_t status = AWS_IOT_JOBS_STATUS_PENDING;
    _jobsOperation_t operation = { .link = { 0 } };
    AwsIotJobsRequestInfo_t requestInfo = AWS_IOT_JOBS_REQUEST_INFO_INITIALIZER;
    AwsIotJobsUpdateInfo_t updateInfo = AWS_IOT_JOBS_UPDATE_INFO_INITIALIZER;
    const char * pJsonValue = NULL;
    size_t jsonValueLength = 0;

    /* Generate request with status details. */
    updateInfo.pStatusDetails = "{\"status\":0}";
    updateInfo.statusDetailsLength = 12;

    status = _AwsIotJobs_GenerateJsonRequest( JOBS_START_NEXT,
                                              &requestInfo,
                                              &updateInfo,
                                              &operation );
    TEST_ASSERT_EQUAL( AWS_IOT_JOBS_SUCCESS, status );

    /* Check that the status details are present. */
    TEST_ASSERT_EQUAL_INT( true, IotJsonUtils_FindJsonValue( operation.pJobsRequest,
                                                             operation.jobsRequestLength,
                                                             "statusDetails",
                                                             13,
                                                             &pJsonValue,
                                                             &jsonValueLength ) );
    TEST_ASSERT_EQUAL( 12, jsonValueLength );
    TEST_ASSERT_EQUAL_STRING_LEN( "{\"status\":0}", pJsonValue, 12 );

    /* Free request document generated by serializer. */
    AwsIotJobs_FreeString( ( void * ) operation.pJobsRequest );

    /* Generate request with status details, step timeout, and custom client token. */
    updateInfo.stepTimeoutInMinutes = 10080;
    requestInfo.pClientToken = "test";
    requestInfo.clientTokenLength = 4;

    status = _AwsIotJobs_GenerateJsonRequest( JOBS_START_NEXT,
                                              &requestInfo,
                                              &updateInfo,
                                              &operation );
    TEST_ASSERT_EQUAL( AWS_IOT_JOBS_SUCCESS, status );

    /* Check that the status details are present. */
    TEST_ASSERT_EQUAL_INT( true, IotJsonUtils_FindJsonValue( operation.pJobsRequest,
                                                             operation.jobsRequestLength,
                                                             "statusDetails",
                                                             13,
                                                             &pJsonValue,
                                                             &jsonValueLength ) );
    TEST_ASSERT_EQUAL( 12, jsonValueLength );
    TEST_ASSERT_EQUAL_STRING_LEN( "{\"status\":0}", pJsonValue, 12 );

    /* Check that step timeout is present. */
    TEST_ASSERT_EQUAL_INT( true, IotJsonUtils_FindJsonValue( operation.pJobsRequest,
                                                             operation.jobsRequestLength,
                                                             "stepTimeoutInMinutes",
                                                             20,
                                                             &pJsonValue,
                                                             &jsonValueLength ) );
    TEST_ASSERT_EQUAL( 5, jsonValueLength );
    TEST_ASSERT_EQUAL_STRING_LEN( "10080", pJsonValue, 5 );

    /* Check that the custom client token is present. */
    TEST_ASSERT_EQUAL_INT( true, IotJsonUtils_FindJsonValue( operation.pJobsRequest,
                                                             operation.jobsRequestLength,
                                                             AWS_IOT_CLIENT_TOKEN_KEY,
                                                             AWS_IOT_CLIENT_TOKEN_KEY_LENGTH,
                                                             &pJsonValue,
                                                             &jsonValueLength ) );
    TEST_ASSERT_EQUAL_PTR( pJsonValue, operation.pClientToken );
    TEST_ASSERT_EQUAL( 6, operation.clientTokenLength );
    TEST_ASSERT_EQUAL_STRING_LEN( "\"test\"", pJsonValue, 6 );

    /* Free request document generated by serializer. */
    AwsIotJobs_FreeString( ( void * ) operation.pJobsRequest );
}

/*-----------------------------------------------------------*/
