@startuml "jobs_demo"
skinparam classFontSize 8
skinparam classFontName Helvetica
autonumber

participant "Main Thread" as main
participant "Notify Next Callback" as cb
participant "Update Callback" as ucb
participant "Jobs Library" as lib

box "Thing" #LightBlue
    participant main
    participant ucb
    participant cb
    participant lib
end box

participant "Server" as server

main -> lib: Register Notify Next Callback

loop Until Exit Command Succeeds
    server -> lib: New Job is Created
    lib -> cb: Callback Invoked
    cb -// lib: StartNextAsync
    cb -> cb: Execute Command from Job Document
    cb -// lib: UpdateAsync with Command Result Result
    lib -> ucb: Result of Update Call

    group Exit Command Successfully Updated
        ucb -> main: Signal end of demo (via flag)
    end
end

@enduml