@startuml
skinparam classFontSize 8
skinparam classFontName Helvetica
autonumber

participant "System" as system
participant "MQTT Receive Callback" as mqtt_receive
participant "Other MQTT functions" as mqtt_other

-> system: 1 complete packet\nand 1 partial packet\nfrom network
activate system
system -> system: Allocate pReceivedData
group pReceivedData owned by system
system -> system: Read packets into\npReceivedData
end

group pReceivedData owned by the MQTT library
system -> mqtt_receive: Call MQTT receive\ncallback
deactivate system

activate mqtt_receive
mqtt_receive -> mqtt_receive: Process complete packet\nin pReceivedData
mqtt_receive -> mqtt_other: Pass complete packet
activate mqtt_other
mqtt_receive -> mqtt_receive: Detect partial packet
mqtt_receive -> system: Return bytes processed
deactivate mqtt_receive
activate system
end
group pReceivedData owned by system
mqtt_other -> mqtt_other: Handle complete packet;\ndon't call freeReceivedData
deactivate mqtt_other
-> system: Remainder of partial\npacket from network
system -> system: Read remainder of\npacket in pReceivedData.\nOverwrite bytes processed.
end
group pReceivedData owned by MQTT library
system -> mqtt_receive: Call MQTT receive callback
deactivate system
end
@enduml
