@startuml
skinparam classFontSize 8
skinparam classFontName Helvetica
autonumber

box "Application" #LightGreen
    participant "Application code" as application
    create participant "MQTT API\nfunction" as api
end box

box "Network stack" #Orange
    participant "Receive\ncallback" as receive_callback
    participant "Network IO" as network
end box

== Send MQTT packet ==
activate application
application -> api: Call MQTT\noperation\nfunction
deactivate application
activate api
api -> api: Allocate resources\nand generate\nMQTT packet
api -> network: Transmit\n MQTT packet
api -> api: Mark operation\nas awaiting response
api -> application: Return\nSTATUS_PENDING
destroy api
activate application
activate network
network -> : Send data to server

== Parse Server Response ==
network <- : Server response
network -> receive_callback: Notify of response
deactivate network
activate receive_callback
receive_callback -> receive_callback: Parse incoming packet
receive_callback -> application: Notify of result
deactivate receive_callback
deactivate application

@enduml
