@startuml
skinparam classFontSize 8
skinparam classFontName Helvetica
autonumber

box "Demo Application" #LightBlue
    participant "Main demo thread" as main
    participant "Credentials callback" as credentials_callback
    participant "Provisioning response callback" as provision_callback
end box


box "Provisioning Library" #LightGreen
    participant "API" as library
end box

box "AWS Iot Core service" #LightPink
    participant "Fleet Provisioning MQTT API\n for new credentials" as credentials_api
    participant "Fleet Provisioning MQTT API\n for provisioning device" as provision_api
end box

main -> library: Request new credentials (set credentials callback)
library -> credentials_api: Request new credentials 
credentials_api -> library: Send new credentials
library -> credentials_callback: Invoke callback with server response
note left of credentials_callback: Print credentials, and \nstore <b>certificate ID</b> and \n<b>certificate ownership token</b>

main -> library: Request provisioning of device (set provisioning response callback)
note left of main: Provides\n1.Certificate ID and Token\n stored in credentials callback\n2.Template Name (defined in demo config)\n3.Device Parameters (defined in demo app)
library -> provision_api: Request provisioning  
note right of provision_api: Register <b>certificate</b>,\nattach <b>policy</n>,\ncreate <b>Thing</b> resource,\nand attach certificate to Thing.
provision_api -> library: Send Thing Name,\nand Device Configuration (specified in Provisioning Template)
library -> provision_callback: Invoke callback with server response
note left of provision_callback: Prints the server response

@enduml
