version: '2'

services:
    httpbin:
      image: kennethreitz/httpbin
      ports:
       - 80:80
    httpbin-ssl:
      image: fsouza/docker-ssl-proxy
      volumes:
        - ../../demos/certificates:/etc/nginx/certs
      environment:
        DOMAIN: localhost
        TARGET_HOST: httpbin
        TARGET_PORT: 80
        SSL_PORT: 443
      links:
        - httpbin
      ports:
        - 443:443
    mosquitto:
      image: eclipse-mosquitto
      ports:
        - 1883:1883
    mosquitto-ssl:
      image: eclipse-mosquitto
      volumes:
        - ../../demos/certificates:/mosquitto/certs
        - .:/mosquitto/config
      ports:
        - 8883:8883
