name: Demo Runner

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-run-demos:
    name: Build and Run Demos
    runs-on: ubuntu-20.04
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install CMake
        run: |
          sudo apt-get install -y libmosquitto-dev
          curl https://cmake.org/files/v3.2/cmake-3.2.0-Linux-x86_64.tar.gz -o cmake.tar.gz
          tar -xf cmake.tar.gz

      - name: Start local MQTT broker
        uses: jasonpcarroll/CI-CD-GitHub-Actions/mqtt-broker-mosquitto@main

      - name: Configure CMake build for MQTT PlainText Demo
        run: |
          mkdir build && cd build
          ../cmake-3.2.0-Linux-x86_64/bin/cmake .. \
          -G "Unix Makefiles" \
          -DBUILD_DEMOS=1 \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_FLAGS='-Wall -Wextra -Werror' \
          -DAWS_IOT_ENDPOINT="aws-iot-endpoint" \
          -DBROKER_ENDPOINT="test.mosquitto.org" \
          -DCLIENT_CERT_PATH="cert/path" \
          -DROOT_CA_CERT_PATH="cert/path" \
          -DCLIENT_PRIVATE_KEY_PATH="key/path" \
          -DCLIENT_IDENTIFIER="ci-identifier" \
          -DTHING_NAME="thing-name" \
          -DS3_PRESIGNED_GET_URL="get-url" \
          -DS3_PRESIGNED_PUT_URL="put-url" \
          -DCLAIM_CERT_PATH="cert/path" \
          -DCLAIM_PRIVATE_KEY_PATH="key/path" \
          -DPROVISIONING_TEMPLATE_NAME="template-name" \
          -DDEVICE_SERIAL_NUMBER="00000" \
          -DCSR_SUBJECT_NAME="CN=Fleet Provisioning Demo" \
          -DGREENGRASS_ADDRESS="greengrass-address"

      - name: Build the MQTT Plaintext Demo
        run: cd build && make mqtt_demo_plaintext
