name: Doxygen Generation
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  doxygen-generation:
    runs-on: ubuntu-20.04
    steps:
      - name: Doxygen generation
        uses: FreeRTOS/CI-CD-Github-Actions/doxygen-generation@main
        with:
          generate_command: |
            git submodule update --init --depth 1
            if python3 tools/doxygen/generate_docs.py --root . ; then
              find * -type d -wholename '*/doxygen/output' -exec mkdir -p html/{} \; -exec mv {}/html html/{} \;
              cat << END > html/index.html
            <!DOCTYPE html>
            <html>
              <head>
                <meta http-equiv="refresh" content="0; url='docs/doxygen/output/html'" />
              </head>
              <body>
                <p><a href="docs/doxygen/output/html">Click here if page does not redirect.</a></p>
              </body>
            </html>
            END
            else
              exit 1
            fi
          output_dir: html
